//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.20.0
//     from Assets/Assets/RPG Cameras & Controllers/Scripts/Inputs/RPGInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace JohnStairs.RCC.Inputs
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Assets/RPG Cameras & Controllers/Scripts/Inputs/RPGInputActions.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @RPGInputActions: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @RPGInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""RPGInputActions"",
    ""maps"": [
        {
            ""name"": ""Character"",
            ""id"": ""c599e24d-7e56-48ff-b456-3a472f8ee5f5"",
            ""actions"": [
                {
                    ""name"": ""RPGController & RPGMotor"",
                    ""type"": ""Button"",
                    ""id"": ""d324a3e4-2be5-4d52-8162-b70f46318f5e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""515c169c-36ff-49e5-a6ec-5328613fcd6f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true,
                    ""priority"": 0
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Button"",
                    ""id"": ""3e2a2ea5-83cf-4a6c-bc73-a5b40108024c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Strafe"",
                    ""type"": ""Button"",
                    ""id"": ""6e9292cf-e67f-48e1-80ff-d5831b193831"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""a2c152f4-1389-424e-9ca5-55db99f9de04"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Toggle Autorunning"",
                    ""type"": ""Button"",
                    ""id"": ""08715240-5ff8-4e32-b4d9-82fa385682ed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Toggle Walking"",
                    ""type"": ""Button"",
                    ""id"": ""460f9b54-8bc5-4f31-bc99-d0fe8e142629"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Toggle Crouching"",
                    ""type"": ""Button"",
                    ""id"": ""89873a76-118e-4dfe-85c9-3838afaa66f3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""72a89df9-fba8-4885-9e52-2a014b4b5d95"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Dive"",
                    ""type"": ""Button"",
                    ""id"": ""de811c1b-bbd6-4a93-b2af-799417fe5997"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Surface"",
                    ""type"": ""Button"",
                    ""id"": ""cbad99f2-8430-4680-ab8c-c686af112cdc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Rotation Modifier"",
                    ""type"": ""Button"",
                    ""id"": ""87145a03-e58c-49aa-9ba6-a6303643a237"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Move Forward Half 1"",
                    ""type"": ""Button"",
                    ""id"": ""bb0020c9-3394-4b02-8c07-e458595d422d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Move Forward Half 2"",
                    ""type"": ""Button"",
                    ""id"": ""b8fc21fa-69d3-45b7-8e8d-3a9815568584"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Align With Camera"",
                    ""type"": ""Button"",
                    ""id"": ""c9c52604-85af-4b1f-85c5-304d113bc79d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Pause Camera Rotation"",
                    ""type"": ""Button"",
                    ""id"": ""5de6b4ec-9506-4886-b528-2eeda0c34e83"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Cancel Climbing"",
                    ""type"": ""Button"",
                    ""id"": ""b4cb3065-ec0f-4a39-8726-ffd6a50825cd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""RPGCamera"",
                    ""type"": ""Button"",
                    ""id"": ""4d999cff-5a75-4762-84f0-dea09da4d069"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Activate Orbiting"",
                    ""type"": ""Button"",
                    ""id"": ""0ac13cc5-909c-4a37-95b2-0e3a054f52c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Activate Orbiting with Character Rotation"",
                    ""type"": ""Button"",
                    ""id"": ""471ed402-fdf4-4ef8-92de-976caaf4e695"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Rotation Amount"",
                    ""type"": ""Value"",
                    ""id"": ""4f84d1f3-0d23-4f68-9747-8e0948b3ec90"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true,
                    ""priority"": 0
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e0212761-50a4-4adb-99c6-27a190a857de"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Zoom To Min Distance"",
                    ""type"": ""Button"",
                    ""id"": ""ca69aa92-5ef0-4631-a435-d589ebd403ca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Zoom To Max Distance"",
                    ""type"": ""Button"",
                    ""id"": ""2c2e5781-b98a-4ef6-8278-d1ce7d2e7d92"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Toggle Menu Cursor"",
                    ""type"": ""Button"",
                    ""id"": ""32b9965b-d7e4-48ed-9e17-70e8fbb78bf2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""24ef1845-e255-4037-84cd-f656a6219b99"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""daeb76dd-4b91-4c4b-abe1-c0f0e03344e9"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1ec56458-9645-4afa-88fb-6f8c54ada361"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cea906e0-4c43-43cd-b153-d364a4aba9ea"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9620a2d4-f1fb-4930-8a0b-1b4b66ffe6cb"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""cda56663-e58f-45fb-a0f1-75ac1c574863"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrow Keys"",
                    ""id"": ""c6ed3e07-ca0d-4621-8d52-5078de9ddaad"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""740e1bbc-ebe3-4a9b-99c6-746fec4b7437"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""24bbde62-874e-4001-b09b-931aeab53f0f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a57f9be3-9419-4b74-8e31-265a244754cc"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6343461f-995c-4a5a-93fa-7171ffc1a9b3"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""715f7cde-1928-41d8-843b-4ba70b6d22ee"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""f4307f4c-beee-455a-afdc-09547c87ebb2"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Strafe"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""2c384072-bcbb-4814-8af9-dcc893618706"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Strafe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""69c6882b-45ae-45c5-b0bc-d7241d170a94"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Strafe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b65b99d1-3a7e-4508-84a3-1a0ad058f047"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05e79061-d2af-4022-b415-0e39bee316ee"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b015bb0-1701-49cf-af49-06b0f77647a4"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6bedbe4-7c49-4155-885f-e9d6d27f156b"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""947dd345-0bc6-44e9-8ec4-8ac7a80f1765"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Surface"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""958cfad5-c5df-441b-9611-94f8a0cd3e6a"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Surface"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0076669-9950-49f5-a70d-b482239f2d77"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e27172c2-1f58-4e30-85d4-8d36a8b04a7d"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf47230f-efb9-4dd4-9f55-f44ca9ed55d5"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Autorunning"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd88586f-911b-4d3d-aa90-ced13887418a"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Autorunning"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70078dcd-98a9-4395-9b77-99e7a05cfa7e"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Walking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7edb1e6-d069-45aa-a579-345bfcf51eb0"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation Modifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74d2dbb5-5674-49c8-9688-e06ce215c8e4"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation Modifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efcfcf9b-381a-4dab-b222-b44717a12ee1"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Forward Half 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e592f6f-fc27-4b8f-bace-dad45ee59d3a"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Forward Half 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16cec1cd-b16f-4c8e-8c66-f717a0c0d63f"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Crouching"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c0c90e6-e4bb-45ab-9012-8dc487284457"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Crouching"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad233e80-90dc-456e-8aba-621f681873b2"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Activate Orbiting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3333c72d-a1bb-42fa-9acd-191d0594a4e1"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Activate Orbiting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c05ce67-582f-481e-85b8-c7ee55a7f215"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Activate Orbiting with Character Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a68a78d-cd21-4819-bf8b-a050c8b3a615"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0.05,y=0.05)"",
                    ""groups"": """",
                    ""action"": ""Rotation Amount"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb650481-4c2f-46a8-a432-393265c7328d"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0.15,y=0.15)"",
                    ""groups"": """",
                    ""action"": ""Rotation Amount"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""198b4a87-bdcf-44b7-8ee6-b00419a713f5"",
                    ""path"": ""<Keyboard>/pageUp"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom To Min Distance"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51efbdc5-bfd6-407f-bb0a-ab6244d056c6"",
                    ""path"": ""<Keyboard>/pageDown"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom To Max Distance"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad270857-1679-4231-a106-591b87de82e0"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": ""Clamp(min=-0.1,max=0.1)"",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18450123-5738-4a81-8544-d9e4f40fadcb"",
                    ""path"": ""<Gamepad>/dpad/y"",
                    ""interactions"": """",
                    ""processors"": ""Clamp(min=-0.01,max=0.01)"",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""4f378ca0-0527-4d77-9d21-738d859fab05"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""af3f8350-d7b2-499b-beb9-5d6e5e44c9b6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ee21d915-10b1-47e4-b239-92aae9acfea7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""be411752-266f-429e-bc92-cb3cd7eb77b9"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""81b22da9-1f34-4cb7-9167-e2806de21931"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""2987f7ca-10ba-4766-9fbc-071d0a385941"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7879388c-7d09-4a60-bdb6-8a702d7ce4b2"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Align With Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9a8ab25-0602-4d95-a6cf-4cc5f17d37b1"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Align With Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""deaf077e-a4a5-4a35-82a6-ca987267766c"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause Camera Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d364d9e-17d9-4cbb-8158-1efd7839987c"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom To Min Distance"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2626432-11b6-4a77-9f31-70075b837fdb"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Menu Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58d6ce52-14c2-4e2c-9cfb-3283faaa547b"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Menu Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bcc623bc-38fe-41e2-9666-ebfe0b7e7ce8"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel Climbing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b2b2932-76bc-4690-be87-37845cd068e1"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel Climbing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24e87180-a7a9-4ee6-ae51-ce41ce7e8f10"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Character
            m_Character = asset.FindActionMap("Character", throwIfNotFound: true);
            m_Character_RPGControllerRPGMotor = m_Character.FindAction("RPGController & RPGMotor", throwIfNotFound: true);
            m_Character_Movement = m_Character.FindAction("Movement", throwIfNotFound: true);
            m_Character_Rotate = m_Character.FindAction("Rotate", throwIfNotFound: true);
            m_Character_Strafe = m_Character.FindAction("Strafe", throwIfNotFound: true);
            m_Character_Jump = m_Character.FindAction("Jump", throwIfNotFound: true);
            m_Character_ToggleAutorunning = m_Character.FindAction("Toggle Autorunning", throwIfNotFound: true);
            m_Character_ToggleWalking = m_Character.FindAction("Toggle Walking", throwIfNotFound: true);
            m_Character_ToggleCrouching = m_Character.FindAction("Toggle Crouching", throwIfNotFound: true);
            m_Character_Sprint = m_Character.FindAction("Sprint", throwIfNotFound: true);
            m_Character_Dive = m_Character.FindAction("Dive", throwIfNotFound: true);
            m_Character_Surface = m_Character.FindAction("Surface", throwIfNotFound: true);
            m_Character_RotationModifier = m_Character.FindAction("Rotation Modifier", throwIfNotFound: true);
            m_Character_MoveForwardHalf1 = m_Character.FindAction("Move Forward Half 1", throwIfNotFound: true);
            m_Character_MoveForwardHalf2 = m_Character.FindAction("Move Forward Half 2", throwIfNotFound: true);
            m_Character_AlignWithCamera = m_Character.FindAction("Align With Camera", throwIfNotFound: true);
            m_Character_PauseCameraRotation = m_Character.FindAction("Pause Camera Rotation", throwIfNotFound: true);
            m_Character_CancelClimbing = m_Character.FindAction("Cancel Climbing", throwIfNotFound: true);
            m_Character_RPGCamera = m_Character.FindAction("RPGCamera", throwIfNotFound: true);
            m_Character_ActivateOrbiting = m_Character.FindAction("Activate Orbiting", throwIfNotFound: true);
            m_Character_ActivateOrbitingwithCharacterRotation = m_Character.FindAction("Activate Orbiting with Character Rotation", throwIfNotFound: true);
            m_Character_RotationAmount = m_Character.FindAction("Rotation Amount", throwIfNotFound: true);
            m_Character_Zoom = m_Character.FindAction("Zoom", throwIfNotFound: true);
            m_Character_ZoomToMinDistance = m_Character.FindAction("Zoom To Min Distance", throwIfNotFound: true);
            m_Character_ZoomToMaxDistance = m_Character.FindAction("Zoom To Max Distance", throwIfNotFound: true);
            m_Character_ToggleMenuCursor = m_Character.FindAction("Toggle Menu Cursor", throwIfNotFound: true);
            m_Character_Attack = m_Character.FindAction("Attack", throwIfNotFound: true);
        }

        ~@RPGInputActions()
        {
            UnityEngine.Debug.Assert(!m_Character.enabled, "This will cause a leak and performance issues, RPGInputActions.Character.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Character
        private readonly InputActionMap m_Character;
        private List<ICharacterActions> m_CharacterActionsCallbackInterfaces = new List<ICharacterActions>();
        private readonly InputAction m_Character_RPGControllerRPGMotor;
        private readonly InputAction m_Character_Movement;
        private readonly InputAction m_Character_Rotate;
        private readonly InputAction m_Character_Strafe;
        private readonly InputAction m_Character_Jump;
        private readonly InputAction m_Character_ToggleAutorunning;
        private readonly InputAction m_Character_ToggleWalking;
        private readonly InputAction m_Character_ToggleCrouching;
        private readonly InputAction m_Character_Sprint;
        private readonly InputAction m_Character_Dive;
        private readonly InputAction m_Character_Surface;
        private readonly InputAction m_Character_RotationModifier;
        private readonly InputAction m_Character_MoveForwardHalf1;
        private readonly InputAction m_Character_MoveForwardHalf2;
        private readonly InputAction m_Character_AlignWithCamera;
        private readonly InputAction m_Character_PauseCameraRotation;
        private readonly InputAction m_Character_CancelClimbing;
        private readonly InputAction m_Character_RPGCamera;
        private readonly InputAction m_Character_ActivateOrbiting;
        private readonly InputAction m_Character_ActivateOrbitingwithCharacterRotation;
        private readonly InputAction m_Character_RotationAmount;
        private readonly InputAction m_Character_Zoom;
        private readonly InputAction m_Character_ZoomToMinDistance;
        private readonly InputAction m_Character_ZoomToMaxDistance;
        private readonly InputAction m_Character_ToggleMenuCursor;
        private readonly InputAction m_Character_Attack;
        /// <summary>
        /// Provides access to input actions defined in input action map "Character".
        /// </summary>
        public struct CharacterActions
        {
            private @RPGInputActions m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public CharacterActions(@RPGInputActions wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Character/RPGControllerRPGMotor".
            /// </summary>
            public InputAction @RPGControllerRPGMotor => m_Wrapper.m_Character_RPGControllerRPGMotor;
            /// <summary>
            /// Provides access to the underlying input action "Character/Movement".
            /// </summary>
            public InputAction @Movement => m_Wrapper.m_Character_Movement;
            /// <summary>
            /// Provides access to the underlying input action "Character/Rotate".
            /// </summary>
            public InputAction @Rotate => m_Wrapper.m_Character_Rotate;
            /// <summary>
            /// Provides access to the underlying input action "Character/Strafe".
            /// </summary>
            public InputAction @Strafe => m_Wrapper.m_Character_Strafe;
            /// <summary>
            /// Provides access to the underlying input action "Character/Jump".
            /// </summary>
            public InputAction @Jump => m_Wrapper.m_Character_Jump;
            /// <summary>
            /// Provides access to the underlying input action "Character/ToggleAutorunning".
            /// </summary>
            public InputAction @ToggleAutorunning => m_Wrapper.m_Character_ToggleAutorunning;
            /// <summary>
            /// Provides access to the underlying input action "Character/ToggleWalking".
            /// </summary>
            public InputAction @ToggleWalking => m_Wrapper.m_Character_ToggleWalking;
            /// <summary>
            /// Provides access to the underlying input action "Character/ToggleCrouching".
            /// </summary>
            public InputAction @ToggleCrouching => m_Wrapper.m_Character_ToggleCrouching;
            /// <summary>
            /// Provides access to the underlying input action "Character/Sprint".
            /// </summary>
            public InputAction @Sprint => m_Wrapper.m_Character_Sprint;
            /// <summary>
            /// Provides access to the underlying input action "Character/Dive".
            /// </summary>
            public InputAction @Dive => m_Wrapper.m_Character_Dive;
            /// <summary>
            /// Provides access to the underlying input action "Character/Surface".
            /// </summary>
            public InputAction @Surface => m_Wrapper.m_Character_Surface;
            /// <summary>
            /// Provides access to the underlying input action "Character/RotationModifier".
            /// </summary>
            public InputAction @RotationModifier => m_Wrapper.m_Character_RotationModifier;
            /// <summary>
            /// Provides access to the underlying input action "Character/MoveForwardHalf1".
            /// </summary>
            public InputAction @MoveForwardHalf1 => m_Wrapper.m_Character_MoveForwardHalf1;
            /// <summary>
            /// Provides access to the underlying input action "Character/MoveForwardHalf2".
            /// </summary>
            public InputAction @MoveForwardHalf2 => m_Wrapper.m_Character_MoveForwardHalf2;
            /// <summary>
            /// Provides access to the underlying input action "Character/AlignWithCamera".
            /// </summary>
            public InputAction @AlignWithCamera => m_Wrapper.m_Character_AlignWithCamera;
            /// <summary>
            /// Provides access to the underlying input action "Character/PauseCameraRotation".
            /// </summary>
            public InputAction @PauseCameraRotation => m_Wrapper.m_Character_PauseCameraRotation;
            /// <summary>
            /// Provides access to the underlying input action "Character/CancelClimbing".
            /// </summary>
            public InputAction @CancelClimbing => m_Wrapper.m_Character_CancelClimbing;
            /// <summary>
            /// Provides access to the underlying input action "Character/RPGCamera".
            /// </summary>
            public InputAction @RPGCamera => m_Wrapper.m_Character_RPGCamera;
            /// <summary>
            /// Provides access to the underlying input action "Character/ActivateOrbiting".
            /// </summary>
            public InputAction @ActivateOrbiting => m_Wrapper.m_Character_ActivateOrbiting;
            /// <summary>
            /// Provides access to the underlying input action "Character/ActivateOrbitingwithCharacterRotation".
            /// </summary>
            public InputAction @ActivateOrbitingwithCharacterRotation => m_Wrapper.m_Character_ActivateOrbitingwithCharacterRotation;
            /// <summary>
            /// Provides access to the underlying input action "Character/RotationAmount".
            /// </summary>
            public InputAction @RotationAmount => m_Wrapper.m_Character_RotationAmount;
            /// <summary>
            /// Provides access to the underlying input action "Character/Zoom".
            /// </summary>
            public InputAction @Zoom => m_Wrapper.m_Character_Zoom;
            /// <summary>
            /// Provides access to the underlying input action "Character/ZoomToMinDistance".
            /// </summary>
            public InputAction @ZoomToMinDistance => m_Wrapper.m_Character_ZoomToMinDistance;
            /// <summary>
            /// Provides access to the underlying input action "Character/ZoomToMaxDistance".
            /// </summary>
            public InputAction @ZoomToMaxDistance => m_Wrapper.m_Character_ZoomToMaxDistance;
            /// <summary>
            /// Provides access to the underlying input action "Character/ToggleMenuCursor".
            /// </summary>
            public InputAction @ToggleMenuCursor => m_Wrapper.m_Character_ToggleMenuCursor;
            /// <summary>
            /// Provides access to the underlying input action "Character/Attack".
            /// </summary>
            public InputAction @Attack => m_Wrapper.m_Character_Attack;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Character; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="CharacterActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(CharacterActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="CharacterActions" />
            public void AddCallbacks(ICharacterActions instance)
            {
                if (instance == null || m_Wrapper.m_CharacterActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_CharacterActionsCallbackInterfaces.Add(instance);
                @RPGControllerRPGMotor.started += instance.OnRPGControllerRPGMotor;
                @RPGControllerRPGMotor.performed += instance.OnRPGControllerRPGMotor;
                @RPGControllerRPGMotor.canceled += instance.OnRPGControllerRPGMotor;
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Rotate.started += instance.OnRotate;
                @Rotate.performed += instance.OnRotate;
                @Rotate.canceled += instance.OnRotate;
                @Strafe.started += instance.OnStrafe;
                @Strafe.performed += instance.OnStrafe;
                @Strafe.canceled += instance.OnStrafe;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @ToggleAutorunning.started += instance.OnToggleAutorunning;
                @ToggleAutorunning.performed += instance.OnToggleAutorunning;
                @ToggleAutorunning.canceled += instance.OnToggleAutorunning;
                @ToggleWalking.started += instance.OnToggleWalking;
                @ToggleWalking.performed += instance.OnToggleWalking;
                @ToggleWalking.canceled += instance.OnToggleWalking;
                @ToggleCrouching.started += instance.OnToggleCrouching;
                @ToggleCrouching.performed += instance.OnToggleCrouching;
                @ToggleCrouching.canceled += instance.OnToggleCrouching;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @Dive.started += instance.OnDive;
                @Dive.performed += instance.OnDive;
                @Dive.canceled += instance.OnDive;
                @Surface.started += instance.OnSurface;
                @Surface.performed += instance.OnSurface;
                @Surface.canceled += instance.OnSurface;
                @RotationModifier.started += instance.OnRotationModifier;
                @RotationModifier.performed += instance.OnRotationModifier;
                @RotationModifier.canceled += instance.OnRotationModifier;
                @MoveForwardHalf1.started += instance.OnMoveForwardHalf1;
                @MoveForwardHalf1.performed += instance.OnMoveForwardHalf1;
                @MoveForwardHalf1.canceled += instance.OnMoveForwardHalf1;
                @MoveForwardHalf2.started += instance.OnMoveForwardHalf2;
                @MoveForwardHalf2.performed += instance.OnMoveForwardHalf2;
                @MoveForwardHalf2.canceled += instance.OnMoveForwardHalf2;
                @AlignWithCamera.started += instance.OnAlignWithCamera;
                @AlignWithCamera.performed += instance.OnAlignWithCamera;
                @AlignWithCamera.canceled += instance.OnAlignWithCamera;
                @PauseCameraRotation.started += instance.OnPauseCameraRotation;
                @PauseCameraRotation.performed += instance.OnPauseCameraRotation;
                @PauseCameraRotation.canceled += instance.OnPauseCameraRotation;
                @CancelClimbing.started += instance.OnCancelClimbing;
                @CancelClimbing.performed += instance.OnCancelClimbing;
                @CancelClimbing.canceled += instance.OnCancelClimbing;
                @RPGCamera.started += instance.OnRPGCamera;
                @RPGCamera.performed += instance.OnRPGCamera;
                @RPGCamera.canceled += instance.OnRPGCamera;
                @ActivateOrbiting.started += instance.OnActivateOrbiting;
                @ActivateOrbiting.performed += instance.OnActivateOrbiting;
                @ActivateOrbiting.canceled += instance.OnActivateOrbiting;
                @ActivateOrbitingwithCharacterRotation.started += instance.OnActivateOrbitingwithCharacterRotation;
                @ActivateOrbitingwithCharacterRotation.performed += instance.OnActivateOrbitingwithCharacterRotation;
                @ActivateOrbitingwithCharacterRotation.canceled += instance.OnActivateOrbitingwithCharacterRotation;
                @RotationAmount.started += instance.OnRotationAmount;
                @RotationAmount.performed += instance.OnRotationAmount;
                @RotationAmount.canceled += instance.OnRotationAmount;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
                @ZoomToMinDistance.started += instance.OnZoomToMinDistance;
                @ZoomToMinDistance.performed += instance.OnZoomToMinDistance;
                @ZoomToMinDistance.canceled += instance.OnZoomToMinDistance;
                @ZoomToMaxDistance.started += instance.OnZoomToMaxDistance;
                @ZoomToMaxDistance.performed += instance.OnZoomToMaxDistance;
                @ZoomToMaxDistance.canceled += instance.OnZoomToMaxDistance;
                @ToggleMenuCursor.started += instance.OnToggleMenuCursor;
                @ToggleMenuCursor.performed += instance.OnToggleMenuCursor;
                @ToggleMenuCursor.canceled += instance.OnToggleMenuCursor;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="CharacterActions" />
            private void UnregisterCallbacks(ICharacterActions instance)
            {
                @RPGControllerRPGMotor.started -= instance.OnRPGControllerRPGMotor;
                @RPGControllerRPGMotor.performed -= instance.OnRPGControllerRPGMotor;
                @RPGControllerRPGMotor.canceled -= instance.OnRPGControllerRPGMotor;
                @Movement.started -= instance.OnMovement;
                @Movement.performed -= instance.OnMovement;
                @Movement.canceled -= instance.OnMovement;
                @Rotate.started -= instance.OnRotate;
                @Rotate.performed -= instance.OnRotate;
                @Rotate.canceled -= instance.OnRotate;
                @Strafe.started -= instance.OnStrafe;
                @Strafe.performed -= instance.OnStrafe;
                @Strafe.canceled -= instance.OnStrafe;
                @Jump.started -= instance.OnJump;
                @Jump.performed -= instance.OnJump;
                @Jump.canceled -= instance.OnJump;
                @ToggleAutorunning.started -= instance.OnToggleAutorunning;
                @ToggleAutorunning.performed -= instance.OnToggleAutorunning;
                @ToggleAutorunning.canceled -= instance.OnToggleAutorunning;
                @ToggleWalking.started -= instance.OnToggleWalking;
                @ToggleWalking.performed -= instance.OnToggleWalking;
                @ToggleWalking.canceled -= instance.OnToggleWalking;
                @ToggleCrouching.started -= instance.OnToggleCrouching;
                @ToggleCrouching.performed -= instance.OnToggleCrouching;
                @ToggleCrouching.canceled -= instance.OnToggleCrouching;
                @Sprint.started -= instance.OnSprint;
                @Sprint.performed -= instance.OnSprint;
                @Sprint.canceled -= instance.OnSprint;
                @Dive.started -= instance.OnDive;
                @Dive.performed -= instance.OnDive;
                @Dive.canceled -= instance.OnDive;
                @Surface.started -= instance.OnSurface;
                @Surface.performed -= instance.OnSurface;
                @Surface.canceled -= instance.OnSurface;
                @RotationModifier.started -= instance.OnRotationModifier;
                @RotationModifier.performed -= instance.OnRotationModifier;
                @RotationModifier.canceled -= instance.OnRotationModifier;
                @MoveForwardHalf1.started -= instance.OnMoveForwardHalf1;
                @MoveForwardHalf1.performed -= instance.OnMoveForwardHalf1;
                @MoveForwardHalf1.canceled -= instance.OnMoveForwardHalf1;
                @MoveForwardHalf2.started -= instance.OnMoveForwardHalf2;
                @MoveForwardHalf2.performed -= instance.OnMoveForwardHalf2;
                @MoveForwardHalf2.canceled -= instance.OnMoveForwardHalf2;
                @AlignWithCamera.started -= instance.OnAlignWithCamera;
                @AlignWithCamera.performed -= instance.OnAlignWithCamera;
                @AlignWithCamera.canceled -= instance.OnAlignWithCamera;
                @PauseCameraRotation.started -= instance.OnPauseCameraRotation;
                @PauseCameraRotation.performed -= instance.OnPauseCameraRotation;
                @PauseCameraRotation.canceled -= instance.OnPauseCameraRotation;
                @CancelClimbing.started -= instance.OnCancelClimbing;
                @CancelClimbing.performed -= instance.OnCancelClimbing;
                @CancelClimbing.canceled -= instance.OnCancelClimbing;
                @RPGCamera.started -= instance.OnRPGCamera;
                @RPGCamera.performed -= instance.OnRPGCamera;
                @RPGCamera.canceled -= instance.OnRPGCamera;
                @ActivateOrbiting.started -= instance.OnActivateOrbiting;
                @ActivateOrbiting.performed -= instance.OnActivateOrbiting;
                @ActivateOrbiting.canceled -= instance.OnActivateOrbiting;
                @ActivateOrbitingwithCharacterRotation.started -= instance.OnActivateOrbitingwithCharacterRotation;
                @ActivateOrbitingwithCharacterRotation.performed -= instance.OnActivateOrbitingwithCharacterRotation;
                @ActivateOrbitingwithCharacterRotation.canceled -= instance.OnActivateOrbitingwithCharacterRotation;
                @RotationAmount.started -= instance.OnRotationAmount;
                @RotationAmount.performed -= instance.OnRotationAmount;
                @RotationAmount.canceled -= instance.OnRotationAmount;
                @Zoom.started -= instance.OnZoom;
                @Zoom.performed -= instance.OnZoom;
                @Zoom.canceled -= instance.OnZoom;
                @ZoomToMinDistance.started -= instance.OnZoomToMinDistance;
                @ZoomToMinDistance.performed -= instance.OnZoomToMinDistance;
                @ZoomToMinDistance.canceled -= instance.OnZoomToMinDistance;
                @ZoomToMaxDistance.started -= instance.OnZoomToMaxDistance;
                @ZoomToMaxDistance.performed -= instance.OnZoomToMaxDistance;
                @ZoomToMaxDistance.canceled -= instance.OnZoomToMaxDistance;
                @ToggleMenuCursor.started -= instance.OnToggleMenuCursor;
                @ToggleMenuCursor.performed -= instance.OnToggleMenuCursor;
                @ToggleMenuCursor.canceled -= instance.OnToggleMenuCursor;
                @Attack.started -= instance.OnAttack;
                @Attack.performed -= instance.OnAttack;
                @Attack.canceled -= instance.OnAttack;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="CharacterActions.UnregisterCallbacks(ICharacterActions)" />.
            /// </summary>
            /// <seealso cref="CharacterActions.UnregisterCallbacks(ICharacterActions)" />
            public void RemoveCallbacks(ICharacterActions instance)
            {
                if (m_Wrapper.m_CharacterActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="CharacterActions.AddCallbacks(ICharacterActions)" />
            /// <seealso cref="CharacterActions.RemoveCallbacks(ICharacterActions)" />
            /// <seealso cref="CharacterActions.UnregisterCallbacks(ICharacterActions)" />
            public void SetCallbacks(ICharacterActions instance)
            {
                foreach (var item in m_Wrapper.m_CharacterActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_CharacterActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="CharacterActions" /> instance referencing this action map.
        /// </summary>
        public CharacterActions @Character => new CharacterActions(this);
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Character" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="CharacterActions.AddCallbacks(ICharacterActions)" />
        /// <seealso cref="CharacterActions.RemoveCallbacks(ICharacterActions)" />
        public interface ICharacterActions
        {
            /// <summary>
            /// Method invoked when associated input action "RPGController & RPGMotor" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRPGControllerRPGMotor(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Movement" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnMovement(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Rotate" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRotate(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Strafe" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnStrafe(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnJump(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Toggle Autorunning" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnToggleAutorunning(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Toggle Walking" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnToggleWalking(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Toggle Crouching" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnToggleCrouching(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Sprint" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSprint(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Dive" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDive(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Surface" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSurface(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Rotation Modifier" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRotationModifier(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Move Forward Half 1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnMoveForwardHalf1(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Move Forward Half 2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnMoveForwardHalf2(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Align With Camera" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAlignWithCamera(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Pause Camera Rotation" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnPauseCameraRotation(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Cancel Climbing" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnCancelClimbing(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "RPGCamera" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRPGCamera(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Activate Orbiting" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnActivateOrbiting(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Activate Orbiting with Character Rotation" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnActivateOrbitingwithCharacterRotation(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Rotation Amount" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRotationAmount(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Zoom" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnZoom(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Zoom To Min Distance" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnZoomToMinDistance(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Zoom To Max Distance" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnZoomToMaxDistance(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Toggle Menu Cursor" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnToggleMenuCursor(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Attack" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAttack(InputAction.CallbackContext context);
        }
    }
}
